[workspace]
resolver = "2"
members = [
    "easyflow-link",
    "easyflow-rust",
    "easyflow-python",
    "easyflow-config",
    "examples/video_lidar_merge-rust",
]

[workspace.dependencies]
tokio = "1.36.0"
